#!/usr/bin/env node
/**
 * SOM CONNECT — SQL build step
 *
 *   src/db/schema.sql  ─┬─▶  src/db/sql.generated.ts   (runtime bootstrap in Workers)
 *   src/db/seed.sql    ─┴─▶  migrations/0001_init.sql  (wrangler d1 migrations apply)
 *                            migrations/0002_seed.sql
 *
 * Keeping one source of truth means the self-healing runtime bootstrap, local
 * wrangler D1 and production D1 can never drift apart.
 *
 * Usage: node scripts/build-sql.mjs  (also wired to `npm run db:build`)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const read = (p) => readFileSync(join(root, p), 'utf8');

const schemaSql = read('src/db/schema.sql');
const seedSql = read('src/db/seed.sql');

const banner = `// AUTO-GENERATED by scripts/build-sql.mjs — do not edit by hand.
// Source of truth: worker/src/db/schema.sql + worker/src/db/seed.sql
`;

const literal = (sql) => '`' + sql.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';

/**
 * `D1Database.exec()` chokes on SQL files that open with a comment line
 * ("SQL code did not contain a statement"), so the runtime copies are stripped
 * of comments. The on-disk .sql files keep their documentation.
 */
const compact = (sql) =>
  sql
    .split('\n')
    .filter((line) => !line.trim().startsWith('--'))
    .join('\n')
    .replace(/\n{2,}/g, '\n')
    .trim();

const generated = `${banner}
export const SCHEMA_SQL = ${literal(schemaSql)};

/** Comment-free copy used by the runtime bootstrap (D1 exec is comment sensitive). */
export const SCHEMA_EXEC_SQL = ${literal(compact(schemaSql))};

export const SEED_SQL = ${literal(seedSql)};

/** Comment-free copy used by the runtime bootstrap. */
export const SEED_EXEC_SQL = ${literal(compact(seedSql))};

/** Bump when schema.sql changes so isolates re-run the bootstrap check. */
export const SCHEMA_VERSION = '3';
`;

writeFileSync(join(root, 'src/db/sql.generated.ts'), generated);

mkdirSync(join(root, 'migrations'), { recursive: true });
writeFileSync(
  join(root, 'migrations/0001_init.sql'),
  `-- SOM CONNECT — initial schema (generated from src/db/schema.sql)\n${schemaSql}`,
);
writeFileSync(
  join(root, 'migrations/0002_seed.sql'),
  `-- SOM CONNECT — demo seed data (generated from src/db/seed.sql)\n${seedSql}`,
);

// Small helpers so wrangler.toml / tooling can discover the current version.
writeFileSync(
  join(root, 'migrations/README.md'),
  `# D1 migrations

Generated from \`src/db/schema.sql\` and \`src/db/seed.sql\` by \`npm run db:build\`.

Apply locally:  \`npm run db:migrate:local\`
Apply to prod:  \`npm run db:migrate:remote\`

Both the runtime bootstrap in \`src/lib/db.ts\` and these files share the same SQL,
so a fresh worker instance self-heals an empty database automatically.
`,
);

console.log('✔ generated src/db/sql.generated.ts');
console.log('✔ generated migrations/0001_init.sql');
console.log('✔ generated migrations/0002_seed.sql');
